import { useCallback, useEffect, useRef, useState } from 'react';

import { getFallbackRecommendations } from '@/features/recommendations/fallback-recommendations';
import { generateRecommendations } from '@/features/recommendations/recommendation.service';
import { AIServiceError, RecommendationServiceError } from '@/services/ai.errors';
import { saveRecommendations, clearRecommendations as clearStoredRecommendations } from '@/services/storage.service';
import { useAppStore } from '@/store/useAppStore';
import type { MealRecommendation } from '@/types/recommendation';
import type { UserPreferences } from '@/types/preferences';

export type RecommendationStatus = 'idle' | 'loading' | 'success' | 'error';

const LOADING_MESSAGES = [
  'Understanding your taste...',
  'Checking your preferences...',
  'Avoiding your allergens...',
  'Finding something delicious...',
] as const;

export function getLoadingMessage(index: number): string {
  return LOADING_MESSAGES[index % LOADING_MESSAGES.length];
}

function getUserFacingError(error: unknown): string {
  if (error instanceof AIServiceError && error.code === 'MISSING_API_KEY') {
    return 'AI service is not configured yet.';
  }
  return "We couldn't reach our AI chef.";
}

export interface UseRecommendationsResult {
  status: RecommendationStatus;
  error: string | null;
  usedFallback: boolean;
  loadingMessageIndex: number;
  recommendations: MealRecommendation[] | null;
  generate: (options?: { force?: boolean }) => Promise<void>;
  regenerate: () => Promise<void>;
  retry: () => Promise<void>;
}

export function useRecommendations(
  preferences: UserPreferences | null,
  storedRecommendations: MealRecommendation[] | null,
): UseRecommendationsResult {
  const setRecommendations = useAppStore((state) => state.setRecommendations);
  const clearRecommendations = useAppStore((state) => state.clearRecommendations);

  const [status, setStatus] = useState<RecommendationStatus>(() =>
    storedRecommendations && storedRecommendations.length === 3 ? 'success' : 'idle',
  );
  const [error, setError] = useState<string | null>(null);
  const [usedFallback, setUsedFallback] = useState(false);
  const [loadingMessageIndex, setLoadingMessageIndex] = useState(0);

  const isGeneratingRef = useRef(false);
  const hasAutoGeneratedRef = useRef(false);

  useEffect(() => {
    if (status !== 'loading') {
      return;
    }

    const intervalId = setInterval(() => {
      setLoadingMessageIndex((prev) => prev + 1);
    }, 2200);

    return () => clearInterval(intervalId);
  }, [status]);

  const runGeneration = useCallback(
    async (options?: { force?: boolean }) => {
      if (!preferences || isGeneratingRef.current) {
        return;
      }

      if (
        !options?.force &&
        storedRecommendations &&
        storedRecommendations.length === 3
      ) {
        setStatus('success');
        return;
      }

      isGeneratingRef.current = true;
      setStatus('loading');
      setError(null);
      setUsedFallback(false);
      setLoadingMessageIndex(0);

      try {
        const results = await generateRecommendations(preferences);
        setRecommendations(results);
        await saveRecommendations(results);
        setStatus('success');
      } catch (generationError) {
        if (__DEV__) {
          console.warn('[BiteWise] Recommendation generation failed:', generationError);
        }

        try {
          const fallback = getFallbackRecommendations(preferences);
          if (fallback.length === 3) {
            setRecommendations(fallback);
            await saveRecommendations(fallback);
            setUsedFallback(true);
            setStatus('success');
            return;
          }
        } catch (fallbackError) {
          if (__DEV__) {
            console.warn('[BiteWise] Fallback recommendations failed:', fallbackError);
          }
        }

        setStatus('error');
        setError(getUserFacingError(generationError));
      } finally {
        isGeneratingRef.current = false;
      }
    },
    [preferences, setRecommendations, storedRecommendations],
  );

  const generate = useCallback(
    async (options?: { force?: boolean }) => {
      await runGeneration(options);
    },
    [runGeneration],
  );

  const regenerate = useCallback(async () => {
    clearRecommendations();
    await clearStoredRecommendations();
    await runGeneration({ force: true });
  }, [clearRecommendations, runGeneration]);

  const retry = useCallback(async () => {
    await runGeneration({ force: true });
  }, [runGeneration]);

  useEffect(() => {
    if (!preferences) {
      return;
    }

    if (storedRecommendations && storedRecommendations.length === 3) {
      setStatus('success');
      return;
    }

    if (hasAutoGeneratedRef.current) {
      return;
    }

    hasAutoGeneratedRef.current = true;
    void runGeneration();
  }, [preferences, runGeneration, storedRecommendations]);

  return {
    status,
    error,
    usedFallback,
    loadingMessageIndex,
    recommendations: storedRecommendations,
    generate,
    regenerate,
    retry,
  };
}
